INSERT INTO items (theme, name, caption, rank, trivia, filename) VALUES('pets', 'billie', 'Billie', 1, "Hi, my name is Billie. So I am going through my own personal journey of self actualization I don't have to share it with you. Stare at my floppy ears. What do I care. Like me I'm my own dog.", '/data/images/pets/billie.jpg');
INSERT INTO items (theme, name, caption, rank, trivia, filename) VALUES('pets', 'tipsy', 'Tipsy', 2, "Hi, my name is Tipsy. My parents think I love to jump into stranger's cars. But really I am just trying to escape their oppressive regime. Sit, Roll-over, Beg. It never stops.Like me so I can get out of here.", '/data/images/pets/tipsy.jpg');
INSERT INTO items (theme, name, caption, rank, trivia, filename) VALUES('pets', 'billy', 'Billy', 3, "Hi, my name is Billy. Look, I know what you are thinking. Rescue dog. More collateral damage from Government anti-greyhound racing policies. But racing does not define me. I am so much more than that. Hang on. Sniff. Rabbit? Like me and support me through my reinvention process.", '/data/images/pets/billy.jpg');
INSERT INTO items (theme, name, caption, rank, trivia, filename) VALUES('pets', 'bogor', 'Bogor', 4, "Hi, my name is Bogor. I have problems forming close relationships. I don't know why but whenever I reach out, the other party backs away.Like me and watch my ratings spike.", '/data/images/pets/bogor.jpg');
INSERT INTO items (theme, name, caption, rank, trivia, filename) VALUES('pets', 'max_bugger', 'Max Bugger', 5, "Hi, my name is Max Bugger. Just like you don't get to choose your parents, same goes for your name. You do, however, get to choose your career. I chose Canary Testing. I sing so that others may live.Like me before my job ends badly.", '/data/images/pets/max_bugger.jpg');
INSERT INTO items (theme, name, caption, rank, trivia, filename) VALUES('pets', 'deedee', 'DeeDee', 6, "Hi, my name is DeeDee. My master, and I use that term deliberately, trained me to pick up pizza using a little wooden trailer. Like hello, the humiliation of it all. And tips? My paw.Like me so I can at least earn a minimum wage.", '/data/images/pets/deedee.jpg');
INSERT INTO items (theme, name, caption, rank, trivia, filename) VALUES('pets', 'roxy', 'Roxy', 7, "Hi, my name is Roxy. They say you don't own pets, they own you. Actually they don't, but they should. And when it comes to this pets/ownership dichomoty issue, well, neigh, it doesn't getter better than me.Like me so I can take you for a ride.", '/data/images/pets/roxy.jpg');
INSERT INTO items (theme, name, caption, rank, trivia, filename) VALUES('pets', 'capi', 'Capi', 8, "Hi, my name is Capi. I might be small, but look at the size of my backyard. If every dog had this much space we would need four more dog planets.Like me because thousands of climate scientists are actually wrong.", '/data/images/pets/capi.jpg');
INSERT INTO items (theme, name, caption, rank, trivia, filename) VALUES('pets', 'selby', 'Selby', 9, "Hi, my name is Selby. So you're thinking, oh dear, maybe slightly unhinged. But being unhinged is no longer a barrier to success.Like me and we can distort reality together.", '/data/images/pets/selby.jpg');
"INSERT INTO items (theme, name, caption, rank, trivia, filename) VALUES('pets', 'snuggles', 'Snuggles', 10, ""Hi, my name is Snuggles. The reason I am rated so highly is because I have in my posession very interesting photos of the Programmer of this app. 
Like me or the world gets to see them."", '/data/images/pets/snuggles.jpg');"
INSERT INTO items (theme, name, caption, rank, trivia, filename) VALUES('pets', 'neo', 'Neo', 11, "Hi, my name is Neo. So Dad has got all these great photos and picks this one. He reckons I fight too much. But has he ever stopped to think, why? Maybe if he spent more time with me I might be able to work through some of my issues.Like me so I can avoid a life in therapy.", '/data/images/pets/neo.jpg');
INSERT INTO items (theme, name, caption, rank, trivia, filename) VALUES('pets', 'milky', 'Milky', 12, "Hi, my name is Milky. My mother loves me. I mean she really loves me. Really, really loves me.Like me so I can find some space.", '/data/images/pets/milky.jpg');
"INSERT INTO items (theme, name, caption, rank, trivia, filename) VALUES('pets', 'billy_2', 'Billy
', 13, ""Hi, my name is Billy. Frankly the notion that my photo page is being dynamically generated using PHP leaves me speechless. Like where is the error handling, and as for transaction management, well, hum bug. Like me so we can get a real Developer."", '/data/images/pets/billy_2.jpg');"
INSERT INTO items (theme, name, caption, rank, trivia, filename) VALUES('pets', 'ichibaby', 'Ichibaby', 14, "Hi, my name is Ichibaby. So much going on here. Cool name. The prop. The obvious twee metaphor opportunity. But do I need your validation?Like me and reinforce my sense of self worth.", '/data/images/pets/ichibaby.jpg');
INSERT INTO items (theme, name, caption, rank, trivia, filename) VALUES('pets', 'cookie', 'Cookie', 15, "Hi, my name is Cookie. The story of the 21st Century right here. Beauty and love thriving within the external existential threat. Or is it? Maybe Cookie represents the hidden threat that lurks within to steal our personal information? Like me, I don't know the anwser, I'm just a kitten.", '/data/images/pets/cookie.jpg');